connection_throttle: 4000
connection_throttle_limit: 3
timeout: 30000
stats: 498c9d5b-31f6-43c4-b845-eba9beec8ce7
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
network_compression_threshold: 256
servers:
  lobby1:
    motd: |-
      &7         &r&8>&r&7>&r&8> Evee &r&bNetwork &r&c[1.8 - 1.17] &r&8<&r&7<&r&8<&r&f&r
      &r&7 &r&7&k&l!!&r&f &r&a&lSURVIVAL &r&7&k&l!!&r&f &r&e&lBEDWARS &r&7- &r&b&lSKYBLOCK &r&7&k&l!!&r&f &r&c&lARCADE &r&7&k&l!!&r&f&r
    address: 162.55.232.104:38916
    restricted: false
  bedwars:
    motd: '&7        &r&8>&r&7>&r&8> Evee &r&bNetwork Bedwars&r&c[1.8 - 1.17] &r&8<&r&7<&r&8<&r&f&r'
    address: 162.55.242.159:26651
    restricted: false
  skyblock:
    motd: '&7        &r&8>&r&7>&r&8> Evee &r&bNetwork Skyblock&r&c[1.8 - 1.17] &r&8<&r&7<&r&8<&r&f&r'
    address: 162.55.232.104:35704
    restricted: false
player_limit: -1
prevent_proxy_connections: false
server_connect_timeout: 5000
remote_ping_timeout: 5000
forge_support: false
remote_ping_cache: -1
log_commands: false
log_pings: true
ip_forward: true
disabled_commands:
- disabledcommandhere
groups:
  md_5:
  - admin
listeners:
- host: 0.0.0.0:26018
  query_port: 26018
  motd: '&1EVEE NETWORK SERVER'
  max_players: 200
  force_default_server: true
  tab_size: 60
  forced_hosts:
    pvp.md-5.net: pvp
  tab_list: GLOBAL_PING
  bind_local_address: true
  ping_passthrough: false
  query_enabled: false
  proxy_protocol: false
  priorities:
  - lobby1
online_mode: false
